### ISSUE TITLE
does this plugin work with jquery 1.11.0?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mpryvkin/jquery-datatables-row-reordering#28]
```
What steps will reproduce the problem?
1. Simply try to init }).rowReordering();
2.
3.

What is the expected output? I should be able to reorder.
What do you see instead? Undefined is not a function.


What version of the product are you using? 1.2.1
On what operating system? Linux


Please provide any additional information below.


```

Original issue reported on code.google.com by `scottmcd...@gmail.com` on 11 Sep 2014 at 5:18
